services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "4533:4533"
    environment:
      ND_LOGLEVEL: info
      ND_DEVACTIVITYPANEL: "false"
      ND_ENABLEINSIGHTSCOLLECTOR: "false"
      ND_ENABLEEXTERNALSERVICES: "false"
    restart: unless-stopped
    volumes:
      - "${DATA_PATH}:/data"
      - "${MUSIC_PATH}:/music:ro"

